### PR TITLE
Networking fixes. Optimized compression. Length now network byte orde…

### PR DESCRIPTION
**Pull request by gcopeland**
…r encoded.

Please accept these minor changes. It optimizes use of compression, minimizes the padded length section, encodes length as a network byte order int (still allows for long messages), offers minimal DOS protection against extremely long payload lengths, optimizes the TCP buffering, provides cleaner socket shutdown, enables TCP keepalives (making it more NAT router friendly), and offers minor clean up here and there.

If these changes are valued I'm likely to find other minor changes in the future.

If you have questions, please let me know.

### CODE REVIEW

**Comment by stolencatkarma** [comment]
If I read that correctly maximum size is 2,048 byes? That's gonna be way too low for what we are doing. I also see patches to client.py that have nothing to do with networking such as changing the size of the window.

I cannot accept this as it.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by gcopeland** [comment]
As I don't have a working client I don't know what the upper limit it. It is, however, very easy to change. Simply accept it and set the desired upper limit in _mm_constants.py. The variable is MM_MAX_PAYLOAD_SIZE. It's simply a value to prevent malicious payloads of 4294967296 bytes each.

**Comment by stolencatkarma** [comment]
merged manually. thank you for your submission.=D

**Comment by gcopeland** [comment]
Hope more to come. I did see there was a minor mistake made in the merge in the constants.

You have:

MM_MAX_PAYLOAD_SIZE = 2048
MM_MIN_PAYLOAD_COMPRESSION_SIZE = 65535

and I expect you want:
MM_MAX_PAYLOAD_SIZE = 65535
MM_MIN_PAYLOAD_COMPRESSION_SIZE = 128

The MM_MIN_PAYLOAD_COMPRESSION_SIZE constant sets the minimum payload size to consider compression. This is an optimization because if the payload is smaller than this size the compressed output will likely be larger than the uncompressed output. Obviously some tweaking down road may make sense but something around 128 to 256 bytes is going to make for a good estimate.

A value of 65535 for MM_MIN_PAYLOAD_COMPRESSION_SIZE effectively disables compression for all payloads smaller than 64K. Which I expect is not the desired result.

**Comment by stolencatkarma** [comment]
Whoops

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Pull request closed without merging**
