### PR TITLE
Eye candy

### PR DESCRIPTION
**Pull request by Stone94**
adding in gfx I paid for a while back

### CODE REVIEW

**Comment by Stone94** [comment]
Lots of options for UI elements and icons

**Comment by stolencatkarma** [comment]
I like this a lot but when you say you paid for does that mean you can use it in any project? Just want to make sure.

**Comment by Stone94** [comment]
> I like this a lot but when you say you paid for does that mean you can use it in any project? Just want to make sure.

The license agreement said i can use it in as many free or commercial projects as  i want, i just cant redistribute them by themselves (basically putting them up for resale or distributing without the game)

**Comment by Stone94** [comment]
Just clarified, unfortunately im not allowed to redistribute the source files unless they were baked into the game :/

**Pull request closed without merging**
