### PR TITLE
Basic logging, as described, with update for constants as discussed.

### PR DESCRIPTION
**Pull request by gcopeland**
Basic logging, as described, with update for constants as discussed.

### CODE REVIEW

**Comment by stolencatkarma** [comment]
this includes the fixes i merged manually. can you remove those. Rebase and just do the logging stuff?

**Comment by gcopeland** [comment]
https://github.com/stolencatkarma/CataclysmLD/network

This shows that no merge was made back into your repository. The merging is required else git's awareness of the deltas spans to the total aggregate of deltas between repositories. 

So for example, in the graph you can see that I forked, merged your master, merged my changes from the feature branch (logging), and then requested a pull. According to git you have not merged back to your master. As such, the total delta is all deltas on my master against your master.

**Comment by stolencatkarma** [comment]
Ahh okay. Sorry still learning git.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by stolencatkarma** [comment]
Hmm. I'm having trouble seeing where I went wrong.

I had my branch. I did git checkout master; git merge mybranch; git push.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by stolencatkarma** [comment]
So I double checked by installing git on my phone and pulling a fresh copy and it shows all the networking additions I've made and all the other updates I've done as well.
Can you git checkout master and git pull maybe to make sure your master is up to date? I feel like you didn't get those updates yet.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by gcopeland** [comment]
https://help.github.com/articles/merging-a-pull-request/

This is what you did?

**Comment by gcopeland** [comment]
Okay, I think I understand what's going on. The network graph is very telling here. Not sure how you did the initial merge but git doesn't seem to know anything about it.

https://github.com/stolencatkarma/CataclysmLD/network

If we look at the graph you can see my initial fork. You then made many updates on your master. Which apparently includes manual (non-merged) changes from my master. ... not finishing since you got it figured out.

The confusion was that your repo didn't understand that a merge had been made. So the delta sets it was making was the sum of the deltas.

That's it! Good Job! I see the network map looks right now.

**Pull request merged**
